name: lotus
channels:
   - conda-forge
   - bioconda
   - defaults
dependencies:
   - python==3.8.3
   - numpy
   - matplotlib
   - pytest
   - requests
   - more-itertools
   - pandas
   - pyfastx
   - tqdm
   - upsetplot
